# dein {{{
[[plugins]]
repo = 'Shougo/dein.vim'
# }}}
# denops {{{
[[plugins]]
repo = 'vim-denops/denops.vim'
# }}}
# guise.vim {{{
[[plugins]]
repo = 'lambdalisue/guise.vim'
# }}}
# heirline {{{
[[plugins]]
repo = 'rebelot/heirline.nvim'
# }}}
# vim: fdm=marker
